title: Hannah VanVels
source: .
destination: ../build
baseurl: ""

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-archives

jekyll-archives:
  enabled:
    - tags
    - categories
  layouts:
    tag: 'tag'
    category: 'category'
  permalinks:
    tag: '/tag/:name/'
    category: '/category/:name/'