title: Hannah VanVels
source: .
destination: ../build
baseurl: ""
permalink: /thoughts/category/:categories/:title/

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-archives

jekyll-archives:
  enabled:
    - tags
    - categories
  layouts:
    tag: 'tag'
    category: 'category'
  permalinks:
    tag: '/thoughts/tag/:name/'
    category: '/thoughts/category/:name/'

algolia:
  application_id: 7WBOAC6Y9S
  index_name: 'HannahVanVels.com'