title: slog
source: .
destination: ../build
baseurl: "/blog"
url: ""
permalink: /posts/:title-:short-year:month:day
markdown: kramdown
paginate: 50
paginate_path: "/p/:num"
plugins:
  - jekyll-paginate
defaults:
  - scope:
      path: ""
    values:
      layout: "default"